name = "SatelliteToolboxLegendre"
uuid = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
license = "MIT"
desc = "Methods to compute Legendre associated functions and their derivatives."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.0.3"

[compat]
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
